### ISSUE TITLE
only authorize the facilitator to shift the retro to the action items stage

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#46]
As a retrospective participant who doesn't want to have to worry about the flow of the retro,
I want the retrospective facilitator to manage the shift from idea generation to action item generation,
So that I can focus my full attention on participating.

__Pre-Reqs:__
  - [x] introduce facilitator role (#45)
  - [x] toggle ability to submit action items (#43)

__Acceptance Criteria:__
  
  - [ ] the checkbox toggle that reads "Toggle Action Items" only appears to the user with the facilitator role
    - __Helpful Tip:__ every user passed down to the Room component within the `users` prop contains a `facilitator` boolean attribute. 
  - [ ] when the facilitator switches the "Toggle Action Items" into the 'on' state, all retro participants enter the action item interface (described in the criteria for #43) in realtime.
  - [ ] when the facilitator switches the "Toggle Action Items" into the 'off' state, all retro participants return to the idea generation interface in real time.

**Comment by vanderhoop** [comment]
implemented
